export const GET_APPLICATIONS = "GET_APPLICATIONS"
export const GET_POST_APPLICATIONS = "GET_POST_APPLICATIONS"
export const GET_ONE_APPLICATION = 'GET_ONE_APPLICATION'
export const GET_MY_APPLICATIONS = 'GET_MY_APPLICATIONS'